### ISSUE TITLE
Missing support for --flat false option

### ISSUE THREAD

**Issue by bart-rosseel-axa** [jroquelaure/jfrog-vso-extension#4]
The invoke command for the JFrog CLI does not support use of the --flat false command line argument. Which prevents me from deploying files to Artifactory and retaining their folder structure. Should be solvable easily by adding the argument to the invoke tool command.

It can even, be solved by adding generic support for the CLI arguments, using a single optional textfield where all arguments can be configured and which is included in the Invoke-Tool call.

**Comment by jroquelaure** [comment]
Thanks for your comment. Please note this project has moved under JFrog official repository : https://github.com/jfrog/jfrog-vso-extension . We are currently working on a rework of this extension to leverage integration with the cli and Artifactory.

**Comment by bart-rosseel-axa** [comment]
Ok thanks. FYI I think adding support for uploading and retaining folder structures from VSTS towards Artifactory using the cli will require a change at level of the cli itself. So we can provide an absolute contents path, but additionally specify which part of that absolute path needs to be retained in Artifactory. Calling the cli from a powershell running in VSTS makes it impossible to provide a relative folder path as contents.
